### ISSUE TITLE
Not works on 3083?

### ISSUE THREAD

**Issue by tunnckoCore** [aziz/SublimeSyncedSidebarBg#2]
Just installed it and it seems it not works.

**Comment by chrisyellostudio** [comment]
+1

Previously installed before ST3 update and showing a black background, re-installed package and I'm getting the same thing.

**Comment by aziz** [comment]
Can't recreate this bug, I've tested it on 3083 and 3092 and it works just fine. 
Check the console see if you've any error. report them here if you have any.

**Comment by tunnckoCore** [comment]
> Check the console see if you've any error.

yea I checked before open an issue and nothing.

**Comment by chrisyellostudio** [comment]
Same, no errors the package has loaded fine from the startup log. If it's any help, I'm on Mac OS X 10.10.3 (14D136)?

**Comment by tunnckoCore** [comment]
I'm on centos 6.6

**Comment by rampico** [comment]
Mine is just showing darker than the main window. (on 3083,OSX 10.10.3)
![screen shot 2015-06-05 at 8 24 52 am](https://cloud.githubusercontent.com/assets/4982973/8007997/9419a644-0b5c-11e5-84fa-4aed0042efde.png)
![screen shot 2015-06-05 at 8 25 04 am](https://cloud.githubusercontent.com/assets/4982973/8008006/975c252a-0b5c-11e5-8bdd-b5ae5c213879.png)
![screen shot 2015-06-05 at 8 25 15 am](https://cloud.githubusercontent.com/assets/4982973/8008010/9ac30ec2-0b5c-11e5-8141-0d5c8f05151a.png)
![screen shot 2015-06-05 at 8 25 29 am](https://cloud.githubusercontent.com/assets/4982973/8008018/9f032cce-0b5c-11e5-8c98-392a9fd16104.png)

**Comment by aziz** [comment]
Yes I pushed that change to the repo a couple of days ago but I fixed it now. 
Actually I prefer the sidebar a bit darker, but I should have changed my user settings file rather than changing this behavior for everyone without communicating the change.

**Comment by chrisyellostudio** [comment]
Thanks, I can confirm the default behaviour has returned as expected. Many thanks!

**Comment by tunnckoCore** [comment]
> I can confirm the default behaviour has returned as expected.

Same here.
