### ISSUE TITLE
sidebar effect

### ISSUE THREAD

**Issue by ctf0** [aziz/SublimeSyncedSidebarBg#4]
many thanx for this plugin, right now i have a couple of questions , as u can see in the below ss

![test](https://cloud.githubusercontent.com/assets/7388088/12138191/a59d3f32-b45f-11e5-921d-d2a9cd8c5000.jpg)
- is there away to disable changing the icons tint
- i have no idea why there is a bar @ the top of the sidebar
- can u aswell right some description to what the settings are for ?

ST 3095, OSX 10.9.5

**Comment by ctf0** [comment]
i figured out the first 2 questions, and now i have another one
- how to have a settings to control sidebar icon tint according to the scheme shade "light,dark,medium,etc..."

**Comment by aziz** [comment]
It this mainly a hack that works with the default sublime theme (to be honest it works best on [my variation of the default sublime theme](https://github.com/aziz/SublimeTheme) and you also need to install [Elcapitan theme](https://github.com/iccir/El-Capitan-Theme)). 

Making it work with all themes is nearly impossible. some themes like yours are using color icons that makes tinting useless. the icons are also designed to look good on a specific background. my custom theme uses plain white mono-color icons and I tint them based on the active view color scheme.

**Comment by ctf0** [comment]
yes i understand but what i mean is that the schemes in ST use an algorithm to determine if the current scheme is "light,dark,medium,etc..." , ofcourse not all the schemes out there implement such a thing but its available for anyone to use , 
so i thought maybe we can connect the plugin somehow with that mechanism and change the tint accordingly , which could be through a setting with an array of values that the user can set.
